-- ==============================================================================
-- SADDAM BARBER - كامل كود قاعدة بيانات SUPABASE مع RLS و STORAGE و SEED DATA
-- ==============================================================================
-- يمكنك نسخ هذا الكود وتشغيله بالكامل دفعة واحدة في Supabase SQL Editor.
-- ==============================================================================

-- 1. التهيئات والإضافات المطلوبة
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- دالة التحديث التلقائي لعمود updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==============================================================================
-- 2. إنشاء الجداول
-- ==============================================================================

-- جدول الخدمات (Services)
CREATE TABLE IF NOT EXISTS public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_ar VARCHAR(200) NOT NULL,
  name_en VARCHAR(200) NOT NULL,
  display_name_ar VARCHAR(200),
  category_ar VARCHAR(200),
  description_ar TEXT,
  description_en TEXT,
  price NUMERIC(10, 2) NOT NULL,
  duration_minutes INTEGER NOT NULL,
  image_url TEXT,
  branch_slugs TEXT DEFAULT '' NOT NULL,
  is_featured BOOLEAN DEFAULT true NOT NULL,
  sort_order INTEGER DEFAULT 0 NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- جدول العروض والباقات (Offers)
CREATE TABLE IF NOT EXISTS public.offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_ar VARCHAR(200) NOT NULL,
  title_en VARCHAR(200) NOT NULL,
  description_ar TEXT,
  description_en TEXT,
  details_ar TEXT,
  details_en TEXT,
  old_price NUMERIC(10, 2) NOT NULL,
  new_price NUMERIC(10, 2) NOT NULL,
  image_url TEXT,
  badge_ar VARCHAR(100),
  valid_until TIMESTAMP WITH TIME ZONE,
  sort_order INTEGER DEFAULT 0 NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- جدول الفروع (Branches)
CREATE TABLE IF NOT EXISTS public.branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(100) UNIQUE NOT NULL,
  name_ar VARCHAR(200) NOT NULL,
  listing_name_ar VARCHAR(200),
  badge_ar VARCHAR(100),
  address_ar TEXT NOT NULL,
  landmark_ar TEXT,
  summary_ar TEXT,
  phone_display VARCHAR(60) NOT NULL,
  phone_href VARCHAR(60) NOT NULL,
  whatsapp VARCHAR(40) NOT NULL,
  hours_ar VARCHAR(200) NOT NULL,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  price_list_image TEXT,
  google_rating DOUBLE PRECISION,
  google_reviews INTEGER,
  maps_url TEXT,
  sort_order INTEGER DEFAULT 0 NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- جدول معرض الصور (Gallery Images)
CREATE TABLE IF NOT EXISTS public.gallery_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  src TEXT NOT NULL,
  alt TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0 NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- جدول فريق العمل / الحلاقين (Barbers)
CREATE TABLE IF NOT EXISTS public.barbers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_ar VARCHAR(200) NOT NULL,
  name_en VARCHAR(200) NOT NULL,
  role_ar VARCHAR(200) NOT NULL,
  role_en VARCHAR(200) NOT NULL,
  bio_ar TEXT,
  bio_en TEXT,
  image_url TEXT,
  sort_order INTEGER DEFAULT 0 NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- جدول آراء العملاء (Testimonials)
CREATE TABLE IF NOT EXISTS public.testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR(200) NOT NULL,
  comment_ar TEXT NOT NULL,
  comment_en TEXT,
  rating INTEGER NOT NULL,
  sort_order INTEGER DEFAULT 0 NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- جدول الحجوزات (Appointments)
CREATE TABLE IF NOT EXISTS public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR(200) NOT NULL,
  customer_phone VARCHAR(50) NOT NULL,
  service_id BIGINT,
  service_name VARCHAR(200),
  barber_id BIGINT,
  branch_slug VARCHAR(100),
  appointment_date TIMESTAMP WITH TIME ZONE NOT NULL,
  notes TEXT,
  status VARCHAR(50) DEFAULT 'pending' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- جدول إعدادات ونصوص الموقع (Site Settings)
CREATE TABLE IF NOT EXISTS public.site_settings (
  key VARCHAR(100) PRIMARY KEY,
  value TEXT DEFAULT '' NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- جدول الوسائط المرفوعة (Media Assets)
CREATE TABLE IF NOT EXISTS public.media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL,
  file_url TEXT NOT NULL,
  mime_type VARCHAR(100),
  size_bytes BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- 3. تفعيل Triggers التحديث التلقائي لـ updated_at
-- ==============================================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_services') THEN
    CREATE TRIGGER set_updated_at_services BEFORE UPDATE ON public.services FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_offers') THEN
    CREATE TRIGGER set_updated_at_offers BEFORE UPDATE ON public.offers FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_branches') THEN
    CREATE TRIGGER set_updated_at_branches BEFORE UPDATE ON public.branches FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_gallery_images') THEN
    CREATE TRIGGER set_updated_at_gallery_images BEFORE UPDATE ON public.gallery_images FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_barbers') THEN
    CREATE TRIGGER set_updated_at_barbers BEFORE UPDATE ON public.barbers FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_testimonials') THEN
    CREATE TRIGGER set_updated_at_testimonials BEFORE UPDATE ON public.testimonials FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_appointments') THEN
    CREATE TRIGGER set_updated_at_appointments BEFORE UPDATE ON public.appointments FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_site_settings') THEN
    CREATE TRIGGER set_updated_at_site_settings BEFORE UPDATE ON public.site_settings FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
  END IF;
END $$;

-- ==============================================================================
-- 4. الفهارس (Indexes) لسرعة الأداء
-- ==============================================================================

CREATE INDEX IF NOT EXISTS idx_services_active ON public.services(is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_offers_active ON public.offers(is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_branches_slug ON public.branches(slug);
CREATE INDEX IF NOT EXISTS idx_branches_active ON public.branches(is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_gallery_active ON public.gallery_images(is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_barbers_active ON public.barbers(is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_testimonials_active ON public.testimonials(is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_appointments_date ON public.appointments(appointment_date, status);

-- ==============================================================================
-- 5. إعدادات الأمان وقواعد RLS (Row Level Security)
-- ==============================================================================

-- تفعيل RLS على جميع الجداول
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.barbers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;

-- حذف أي سياسات سابقة لإعادة بنائها بنظافة
DROP POLICY IF EXISTS "Public can view active services" ON public.services;
DROP POLICY IF EXISTS "Admin full access on services" ON public.services;
DROP POLICY IF EXISTS "Public can view active offers" ON public.offers;
DROP POLICY IF EXISTS "Admin full access on offers" ON public.offers;
DROP POLICY IF EXISTS "Public can view active branches" ON public.branches;
DROP POLICY IF EXISTS "Admin full access on branches" ON public.branches;
DROP POLICY IF EXISTS "Public can view active gallery" ON public.gallery_images;
DROP POLICY IF EXISTS "Admin full access on gallery" ON public.gallery_images;
DROP POLICY IF EXISTS "Public can view active barbers" ON public.barbers;
DROP POLICY IF EXISTS "Admin full access on barbers" ON public.barbers;
DROP POLICY IF EXISTS "Public can view active testimonials" ON public.testimonials;
DROP POLICY IF EXISTS "Admin full access on testimonials" ON public.testimonials;
DROP POLICY IF EXISTS "Public can create appointments" ON public.appointments;
DROP POLICY IF EXISTS "Admin full access on appointments" ON public.appointments;
DROP POLICY IF EXISTS "Public can view site settings" ON public.site_settings;
DROP POLICY IF EXISTS "Admin full access on site settings" ON public.site_settings;
DROP POLICY IF EXISTS "Public can view media" ON public.media;
DROP POLICY IF EXISTS "Admin full access on media" ON public.media;

-- السياسات للزوار (Public Access)
CREATE POLICY "Public can view active services" ON public.services
  FOR SELECT USING (is_active = true);

CREATE POLICY "Public can view active offers" ON public.offers
  FOR SELECT USING (is_active = true);

CREATE POLICY "Public can view active branches" ON public.branches
  FOR SELECT USING (is_active = true);

CREATE POLICY "Public can view active gallery" ON public.gallery_images
  FOR SELECT USING (is_active = true);

CREATE POLICY "Public can view active barbers" ON public.barbers
  FOR SELECT USING (is_active = true);

CREATE POLICY "Public can view active testimonials" ON public.testimonials
  FOR SELECT USING (is_active = true);

CREATE POLICY "Public can view site settings" ON public.site_settings
  FOR SELECT USING (true);

CREATE POLICY "Public can view media" ON public.media
  FOR SELECT USING (true);

CREATE POLICY "Public can create appointments" ON public.appointments
  FOR INSERT WITH CHECK (true);

-- السياسات للأدمن المسجل (Authenticated Admin Full Access)
CREATE POLICY "Admin full access on services" ON public.services
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin full access on offers" ON public.offers
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin full access on branches" ON public.branches
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin full access on gallery" ON public.gallery_images
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin full access on barbers" ON public.barbers
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin full access on testimonials" ON public.testimonials
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin full access on appointments" ON public.appointments
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin full access on site settings" ON public.site_settings
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin full access on media" ON public.media
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ==============================================================================
-- 6. إعداد SUPABASE STORAGE (سلة التخزين للصور)
-- ==============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'saddam-media',
  'saddam-media',
  true,
  15728640, -- 15 ميجابايت
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml']
)
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 15728640;

-- سياسات سلة التخزين saddam-media
DROP POLICY IF EXISTS "Public can view storage objects" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated admin can upload storage objects" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated admin can update storage objects" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated admin can delete storage objects" ON storage.objects;

CREATE POLICY "Public can view storage objects" ON storage.objects
  FOR SELECT USING (bucket_id = 'saddam-media');

CREATE POLICY "Authenticated admin can upload storage objects" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'saddam-media' AND (auth.role() = 'authenticated' OR auth.role() = 'anon'));

CREATE POLICY "Authenticated admin can update storage objects" ON storage.objects
  FOR UPDATE USING (bucket_id = 'saddam-media' AND auth.role() = 'authenticated');

CREATE POLICY "Authenticated admin can delete storage objects" ON storage.objects
  FOR DELETE USING (bucket_id = 'saddam-media' AND auth.role() = 'authenticated');

-- ==============================================================================
-- 7. زرع البيانات الافتراضية الأولية (Initial Seed Data)
-- ==============================================================================

-- (أ) الفروع
INSERT INTO public.branches (slug, name_ar, listing_name_ar, badge_ar, address_ar, landmark_ar, summary_ar, phone_display, phone_href, whatsapp, hours_ar, lat, lng, google_rating, google_reviews, maps_url, price_list_image, sort_order, is_active)
VALUES
(
  'hadayek-qobbah',
  'فرع حدائق القبة',
  'صدام باربرشوب',
  'الفرع الرئيسي',
  '87 شارع مصر والسودان، حدائق القبة، القاهرة',
  'Plus Code: 37HH+J6 حدائق القبة',
  'حلاقة وعناية: قص وشعر ودقن وبشرة وشعر وأظافر — بدون ساونا أو جاكوزي.',
  '010 6140 2242',
  'tel:+201061402242',
  '201061402242',
  'يومياً من 11:00 صباحاً حتى 2:00 صباحاً',
  30.0790509,
  31.2780675,
  4.3,
  21,
  'https://maps.app.goo.gl/FvLTtjg1pLMVt4T2A',
  NULL,
  10,
  true
),
(
  'nasr-city',
  'فرع مدينة نصر – عباس العقاد',
  'MS صدام — صالون صدام',
  'VIP MEN EXPERIENCE',
  'شارع عباس العقاد، مدينة نصر، القاهرة',
  'Plus Code: 387P+8M مدينة نصر',
  'VIP MEN EXPERIENCE: الخدمات الأساسية + ساونا علاجية واستيم وحمام مغربي وجاكوزي ومساج.',
  '011 2153 7537',
  'tel:+201121537537',
  '201121537537',
  'يومياً من 11:00 صباحاً حتى 2:30 صباحاً',
  30.0633343,
  31.3366492,
  5.0,
  8,
  'https://maps.app.goo.gl/qFjCxjWv9eCKxH9X7',
  '/images/prices-nasr-city.jpg',
  20,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name_ar = EXCLUDED.name_ar,
  address_ar = EXCLUDED.address_ar,
  phone_display = EXCLUDED.phone_display,
  phone_href = EXCLUDED.phone_href,
  whatsapp = EXCLUDED.whatsapp,
  hours_ar = EXCLUDED.hours_ar;

-- (ب) إعدادات الموقع
INSERT INTO public.site_settings (key, value)
VALUES
('siteNameAr', 'صالون صدام للحلاقة'),
('siteNameEn', 'SADDAM BARBER'),
('logoImage', '/images/IMG_6588.jpeg'),
('footerAbout', 'صالون صدام للحلاقة يقدم تجربة حلاقة فاخرة بأيدي محترفين. نحرص على كل تفصيل لنمنحك المظهر الأنيق الذي تستحقه.'),
('phoneDisplay', '010 6140 2242'),
('phoneHref', 'tel:+201061402242'),
('whatsapp', '201061402242'),
('address', '87 شارع مصر والسودان، حدائق القبة، القاهرة'),
('hours', 'يومياً من 11:00 صباحاً حتى 2:00 صباحاً'),
('email', ''),
('instagram', 'https://instagram.com'),
('facebook', 'https://facebook.com'),
('tiktok', ''),
('whatsappMessage', 'السلام عليكم، عايز أحجز موعد في صالون صدام'),
('heroImage', '/images/hero.jpg'),
('heroKicker', 'SADDAM BARBER'),
('heroTitle', 'SADDAM'),
('heroTitleHighlight', 'BARBER'),
('heroSubtitle', 'مش مجرد حلاقة… دي تجربة صدام'),
('heroTagline', 'VIP MEN EXPERIENCE'),
('heroPrimaryCta', 'احجز موعدك الآن'),
('heroSecondaryCta', 'اكتشف خدماتنا'),
('servicesKicker', 'اختار الفرع الأول'),
('servicesTitle', 'خدمات كل فرع بوضوح'),
('servicesSubtitle', 'مفيش قائمة واحدة ملخبطة: اختار فرعك وهتشوف الخدمات المتاحة فيه فقط، وبعدها احجز الخدمة على واتساب في ضغطة.'),
('offersKicker', 'عروض خاصة'),
('offersTitle', 'عروض العرسان وتجارب VIP'),
('offersSubtitle', 'كل عرض واضح بسعره القديم والجديد وخدماته بالتفصيل. العروض متاحة في فرع مدينة نصر – عباس العقاد، واحجزها مباشرة على واتساب.'),
('galleryKicker', 'من داخل الصالون'),
('galleryTitle', 'معرض الصور'),
('branchesKicker', 'فروعنا'),
('branchesTitle', 'أقرب فرع ليك مستنيك'),
('branchesSubtitle', 'فرعينا في القاهرة: حدائق القبة ومدينة نصر. اختار الفرع الأقرب لك، وشوف مكانه على الخريطة، وكلمنا مباشرة أو احجز على واتساب في ثواني.'),
('bookingKicker', 'احجز موعدك'),
('bookingTitle', 'حجز موعد سريع'),
('bookingSubtitle', 'اختر الخدمة والوقت المناسب لك، وسنقوم بالتواصل معك لتأكيد الحجز.'),
('testimonialsKicker', 'تقييمات حقيقية'),
('testimonialsTitle', 'شوف تقييماتنا على Google'),
('testimonialsSubtitle', 'بدل ما نعرض كلام منسوب لعملاء من غير مصدر، تقدر تشوف التقييمات الحقيقية وتفاصيل كل فرع مباشرة على خرائط Google.')
ON CONFLICT (key) DO NOTHING;

-- (ج) الخدمات الأساسية
INSERT INTO public.services (name_ar, name_en, display_name_ar, category_ar, description_ar, description_en, price, duration_minutes, image_url, branch_slugs, is_featured, sort_order, is_active)
VALUES
('قص شعر (فوطة سخنة وفوطة ساقعه)', 'Haircut (Hot & Cold Towel)', 'قص شعر', 'حلاقة وعناية', 'قص شعر احترافي يناسب شكل وجهك، مع فوطة سخنة قبل القص وفوطة ساقعه بعده.', 'A professional haircut for your face shape, with a hot towel before and a cold towel after.', 250.00, 45, '/images/service-haircut.jpg', '', true, 10, true),
('قص أطفال', 'Kids Haircut', 'قص أطفال', 'حلاقة وعناية', 'قصة شعر مريحة وسريعة للأطفال بتعامل هادي وسعر مناسب.', 'A comfortable, quick haircut for kids at a friendly price.', 200.00, 30, '/images/service-haircut.jpg', '', true, 20, true),
('دقن بخار', 'Steam Beard Shave', 'دقن', 'حلاقة وعناية', 'حلاقة وتشكيل الذقن بالبخار لفتح المسام، بتمريرة ناعمة ومن غير تهيج.', 'Steam shave for a close, smooth beard line without irritation.', 200.00, 30, '/images/service-beard.jpg', '', true, 30, true),
('دقن (فوطة ساقعة)', 'Beard Shave (Cold Towel)', 'دقن فوطة ساقعة', 'حلاقة وعناية', 'تهذيب وتشكيل الذقن بدقة عالية مع فوطة ساقعة بعد الحلاقة.', 'Precise beard trimming and shaping with a cold towel finish.', 150.00, 25, '/images/service-beard.jpg', '', false, 40, true),
('شعر + دقن + سكرب + حمام كريم', 'Haircut + Beard + Scrub + Cream Bath', 'شعر + دقن', 'حلاقة وعناية', 'الباقة الكاملة: قصة شعر وذقن مع سكرب للوجه وفوطتين (سخنة وساقعة) وحمام كريم.', 'The full package: haircut and beard with a face scrub, hot and cold towels, and a cream bath.', 500.00, 90, '/images/service-combo.jpg', '', true, 50, true),
('سشوار', 'Blow Dry', 'سشوار', 'حلاقة وعناية', 'تسريح وتجفيف الشعر بالسيشوار بلمسة نهائية مرتبة.', 'Hair drying and styling with a neat finishing touch.', 150.00, 20, '/images/service-blow-dry-2.jpeg', '', true, 60, true),
('بشرة VIP', 'VIP Facial', 'تنظيف بشرة', 'العناية بالبشرة', 'تنظيف وتفتيح البشرة بمنتجات فاخرة مع ماسك وترطيب عميق ونتيجة واضحة من أول جلسة.', 'Luxury facial cleansing and brightening with a mask and deep hydration.', 500.00, 60, '/images/service-facial.jpg', '', true, 70, true),
('هيدروفاشيال 7 مراحل', 'Hydrafacial (7 Steps)', 'هيدروفاشيال 7 مراحل', 'العناية بالبشرة', 'جلسة هيدروفاشيال بـ7 مراحل لتنظيف البشرة وإزالة الرؤوس السوداء وتجديد النضارة.', 'A 7-step hydrafacial that deep-cleans the skin and restores its glow.', 800.00, 60, '/images/gallery-3.jpg', '', false, 80, true),
('هيدروفاشيال 11 مرحلة', 'Hydrafacial (11 Steps)', 'هيدروفاشيال 11 مرحلة', 'العناية بالبشرة', 'الجلسة الأشمل بـ11 مرحلة عناية بالبشرة، لنتيجة أعمق وثبات أطول.', 'Our most complete skin treatment with 11 steps for deeper, longer-lasting results.', 1200.00, 75, '/images/gallery-1.jpg', '', false, 90, true),
('وكس كامل', 'Full Body Wax', 'وكس', 'وكس وإزالة الشعر', 'إزالة الشعر بالشمع للجسم بالكامل بمنتجات لطيفة على البشرة.', 'Full-body waxing with products that are gentle on the skin.', 200.00, 45, '/images/gallery-2.jpg', '', true, 100, true),
('صبغة شعر', 'Hair Coloring', 'صبغة شعر', 'صبغات وتجميل', 'ألوان عصرية بجودة عالية وثبات طويل ومنتجات آمنة على الشعر.', 'Modern colors with high quality, long-lasting hold and safe products.', 300.00, 90, '/images/service-coloring-saddam.jpeg', '', true, 110, true),
('توبيك', 'Toppik (Hair Coverage)', 'توبيك', 'حلاقة وعناية', 'تغطية فراغات الشعر والمناطق الخفيفة ببودرة توبيك بلون مطابق لشعرك.', 'Covering thin patches with toppik powder in a shade that matches your hair.', 150.00, 30, '/images/service-toppik.jpeg', '', true, 120, true),
('حمام زيت', 'Hot Oil Bath', 'حمام زيت', 'العناية بالشعر', 'حمام زيت دافئ لترطيب الشعر وتغذيته من الجذور للأطراف.', 'A warm oil treatment that nourishes hair from root to tip.', 200.00, 30, '/images/gallery-5.jpg', '', false, 130, true),
('مانيكير يد', 'Manicure', 'مانيكير يد', 'عناية باليدين والقدمين', 'عناية كاملة باليدين: تقشير وترطيب وتهذيب الأظافر.', 'Complete hand care: exfoliation, moisturizing and nail care.', 250.00, 30, '/images/gallery-2.jpg', '', true, 140, true),
('باديكير قدم', 'Pedicure', 'باديكير قدم', 'عناية باليدين والقدمين', 'عناية كاملة بالقدمين: تنظيف وتقشير وترطيب وتشكيل الأظافر.', 'Complete foot care: cleansing, exfoliation, moisturizing and nail shaping.', 350.00, 45, '/images/gallery-2.jpg', '', true, 150, true),
('ساونا علاجية', 'Therapeutic Sauna', 'ساونا علاجية', 'VIP MEN EXPERIENCE', 'جلسة ساونا لفتح المسام وتنشيط الدورة الدموية وتهدئة الجسم.', 'A sauna session to open pores, boost circulation and relax the body.', 400.00, 45, '/images/gallery-5.jpg', 'nasr-city', true, 160, true),
('استيم + ليفة مغربي', 'Steam + Moroccan Loofah', 'استيم + حمام مغربي', 'VIP MEN EXPERIENCE', 'جلسة بخار مع تقشير بالليفة المغربي لتنظيف الجسم بالكامل ونعومة فورية.', 'A steam session with a Moroccan loofah scrub for a full-body clean and instant smoothness.', 500.00, 60, '/images/gallery-1.jpg', 'nasr-city', true, 170, true),
('جاكوزي', 'Jacuzzi', 'جاكوزي', 'VIP MEN EXPERIENCE', 'جلسة جاكوزي مهدئة للعضلات بعد يوم طويل.', 'A calming jacuzzi session to soothe tired muscles.', 350.00, 45, '/images/service-combo.jpg', 'nasr-city', true, 180, true),
('مساج (45 دقيقة – مدرب)', 'Massage (45 min – Trained)', 'مساج', 'VIP MEN EXPERIENCE', 'جلسة مساج 45 دقيقة على إيد مدرب، لاسترخاء العضلات وتخفيف التوتر.', 'A 45-minute massage by a trained therapist to relax muscles and release tension.', 650.00, 45, '/images/service-massage.jpg', 'nasr-city', true, 190, true),
('باديكير علاجي (يد + قدم)', 'Therapeutic Manicure & Pedicure', 'باديكير علاجي (يد + قدم)', 'VIP MEN EXPERIENCE', 'برنامج علاجي متكامل لليدين والقدمين لعلاج الجفاف والتشققات وتشكيل الأظافر.', 'A complete therapeutic program for hands and feet that treats dryness and cracks.', 750.00, 75, '/images/gallery-4.jpg', 'nasr-city', true, 200, true);

-- (د) العروض الخاصة
INSERT INTO public.offers (title_ar, title_en, description_ar, description_en, details_ar, details_en, old_price, new_price, image_url, badge_ar, sort_order, is_active)
VALUES
(
  'عرض العريس VIP 👑',
  'Groom VIP Package',
  'تجربة متكاملة تخليك في أفضل لوك وأعلى استرخاء قبل أهم يوم في حياتك.',
  'A complete grooming and relaxation experience before the biggest day of your life.',
  E'قص شعر.\nدقن بخار.\nتنظيف بشرة (هيدروفيشال 12 مرحلة).\nوكس كامل.\nصبغة شعر.\nتوبيك لفراغات الشعر.\nمانيكير يد + باديكير قدم.\nساونا علاجية واسترخاء.\nاستيم + ليفة مغربي.\nجاكوزي.\nجلسة ترميم شعر.\nمساج 45 دقيقة مع مدرب متخصص.\nسشوار + تثبيت اللوك النهائي.\nحمام كريم.\nمميزات إضافية: لوكر خاص، شاور، غرفة تغيير خاصة، تعقيم كامل وأدوات شخصية.',
  E'Haircut.\nSteam beard treatment.\nHydrofacial skin cleansing (12 stages).\nFull body wax.\nHair coloring.\nTopik for hair gaps.\nHand and foot pedicure.\nSauna and relaxation.\nSteam session + Moroccan bath scrub.\nJacuzzi.\nHair repair session.\n45-minute massage with a specialist therapist.\nBlow-dry + final look styling.\nCream bath treatment.\nExtras: private locker, shower, private changing room, full sterilization and personal tools.',
  5500.00,
  2900.00,
  '/images/offer-groom-2900.jpeg',
  'الباقة الملكية',
  10,
  true
),
(
  'عرض العريس 1',
  'Groom Package 1',
  'تجربة متكاملة تخليك في أفضل لوك وأعلى استرخاء قبل أهم يوم في حياتك.',
  'A complete grooming and relaxation experience before the biggest day of your life.',
  E'قص شعر.\nدقن بخار.\nتنظيف بشرة (هيدروفيشال 7 مراحل).\nوكس كامل.\nصبغة شعر.\nتوبيك لفراغات الشعر.\nمانيكير يد.\nساونا علاجية واسترخاء.\nاستيم + ليفة مغربي.\nجاكوزي.\nمساج 45 دقيقة مع مدرب متخصص.\nحمام كريم + جلسة ترميم شعر.\nسشوار + تثبيت اللوك النهائي.\nمميزات إضافية: لوكر خاص، شاور، غرفة تغيير خاصة، تعقيم كامل وأدوات شخصية.',
  E'Haircut.\nSteam beard treatment.\nHydrofacial skin cleansing (7 stages).\nFull body wax.\nHair coloring.\nTopik for hair gaps.\nHand pedicure.\nSauna and relaxation.\nSteam session + Moroccan bath scrub.\nJacuzzi.\n45-minute massage with a specialist therapist.\nCream bath + hair repair session.\nBlow-dry + final look styling.\nExtras: private locker, shower, private changing room, full sterilization and personal tools.',
  4500.00,
  1800.00,
  '/images/offer-groom-1800.jpeg',
  'الأكثر طلباً',
  20,
  true
),
(
  'عرض العريس 2',
  'Groom Package 2',
  'تجربة متكاملة تخليك في أفضل لوك وأعلى استرخاء قبل أهم يوم في حياتك.',
  'A complete grooming and relaxation experience before the biggest day of your life.',
  E'قص شعر.\nدقن بخار.\nتنظيف بشرة (سيشنال 7 مراحل).\nوكس كامل.\nصبغة شعر.\nتويك.\nمانيكير يد.\nتسبيتات.\nسشوار.\nمميزات إضافية: لوكر خاص، شاور، غرفة تغيير خاصة.\nأسعار شاملة.',
  E'Haircut.\nSteam beard treatment.\nSkin cleansing (7 stages).\nFull body wax.\nHair coloring.\nTopik for hair gaps.\nHand pedicure.\nHair fixing treatment.\nBlow-dry.\nExtras: private locker, shower, private changing room.\nAll-inclusive pricing.',
  2500.00,
  1000.00,
  '/images/offer-groom-1000.jpeg',
  'أسعار شاملة',
  30,
  true
),
(
  'عرض العريس 3',
  'Groom Package 3',
  'محتاج تروق على نفسك؟ الحق عرض العريس 3 بسعر مخفّض.',
  'Need to treat yourself? Grab the Groom Package 3 at a discounted price.',
  E'قص شعر.\nسشوار.\nدقن.\nتنظيف بشرة VIP.',
  E'Haircut.\nBlow-dry.\nBeard grooming.\nVIP skin cleansing.',
  1150.00,
  700.00,
  '/images/offer-saddam-700.jpeg',
  'عرض سريع',
  40,
  true
);

-- (هـ) صور المعرض
INSERT INTO public.gallery_images (src, alt, sort_order, is_active)
VALUES
('/images/gallery-1.jpg', 'جلسة عناية بالذقن مع بخار الوجه وترطيب بالزيت', 10, true),
('/images/gallery-2.jpg', 'تنظيف وتشكيل الأظافر (مانيكير) بعناية في الصالون', 20, true),
('/images/gallery-3.jpg', 'تنظيف عميق للبشرة بالبخار مع تقشير الوجه', 30, true),
('/images/gallery-4.jpg', 'وضع ماسك الوجه بفرشاة احترافية داخل غرفة العناية', 40, true),
('/images/gallery-5.jpg', 'تغذية البشرة بالبخار مع سيروم مرطّب للوجه', 50, true),
('/images/gallery-6.jpg', 'دهان زيت العناية بالبشرة بعد جلسة التنظيف', 60, true);

-- (و) فريق العمل
INSERT INTO public.barbers (name_ar, name_en, role_ar, role_en, bio_ar, bio_en, image_url, sort_order, is_active)
VALUES
('صدّام', 'Saddam', 'مالك وكبير الحلاقين', 'Owner & Master Barber', 'خبرة أكثر من 15 عاماً في فن الحلاقة والعناية بالرجل.', 'Over 15 years of experience in the art of barbering and men''s grooming.', '/images/barber-saddam.jpg', 10, true),
('أحمد', 'Ahmed', 'حلاق محترف', 'Professional Barber', 'متخصص في القصات العصرية والتفاصيل الدقيقة.', 'Specialized in modern cuts and fine details.', '/images/barber-ahmed.jpg', 20, true),
('محمد', 'Mohamed', 'حلاق ذقون', 'Beard Specialist', 'خبير في تهذيب وتشكيل الذقن بأحدث الطرق.', 'Expert in beard trimming and shaping with the latest techniques.', '/images/barber-mohamed.jpg', 30, true);
